In [1]:
!python3 -m pip install pandas


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("house_data.csv")

In [4]:
data.head()

,sqft,bedrooms,bathrooms,age,floors,garage,lot_size,city_index,price
0,1360,2,4,18,1,0,5566,1,248990
1,4272,3,4,29,2,2,2909,0,941769
2,3592,1,4,13,2,1,7364,8,378015
3,966,1,4,19,1,0,3581,0,196887
4,4926,2,4,48,1,1,1691,3,1063441


In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sqft        1000 non-null   int64
 1   bedrooms    1000 non-null   int64
 2   bathrooms   1000 non-null   int64
 3   age         1000 non-null   int64
 4   floors      1000 non-null   int64
 5   garage      1000 non-null   int64
 6   lot_size    1000 non-null   int64
 7   city_index  1000 non-null   int64
 8   price       1000 non-null   int64
dtypes: int64(9)
memory usage: 70.4 KB


In [6]:
X = data.drop(columns=['price'])

In [7]:
X.head()

,sqft,bedrooms,bathrooms,age,floors,garage,lot_size,city_index
0,1360,2,4,18,1,0,5566,1
1,4272,3,4,29,2,2,2909,0
2,3592,1,4,13,2,1,7364,8
3,966,1,4,19,1,0,3581,0
4,4926,2,4,48,1,1,1691,3


In [8]:
Y = data[['price']]

In [9]:
Y.head()

,price
0,248990
1,941769
2,378015
3,196887
4,1063441


In [10]:
type(X)

pandas.DataFrame

In [11]:
!python3 -m pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [12]:
import numpy as np

In [13]:
X_new = X.to_numpy(dtype=np.float32)

In [14]:
Y_new = Y.to_numpy(dtype=np.float32)

In [15]:
type(X_new)

numpy.ndarray

In [16]:
type(Y_new)

numpy.ndarray

In [17]:
X_new

array([[1.360e+03, 2.000e+00, 4.000e+00, ..., 0.000e+00, 5.566e+03,
        1.000e+00],
       [4.272e+03, 3.000e+00, 4.000e+00, ..., 2.000e+00, 2.909e+03,
        0.000e+00],
       [3.592e+03, 1.000e+00, 4.000e+00, ..., 1.000e+00, 7.364e+03,
        8.000e+00],
       ...,
       [2.606e+03, 4.000e+00, 4.000e+00, ..., 1.000e+00, 1.495e+03,
        0.000e+00],
       [4.723e+03, 5.000e+00, 2.000e+00, ..., 0.000e+00, 3.148e+03,
        9.000e+00],
       [3.268e+03, 4.000e+00, 3.000e+00, ..., 2.000e+00, 1.556e+03,
        2.000e+00]], shape=(1000, 8), dtype=float32)

In [18]:
!python3 -m pip install scikit-learn



[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(X_new, Y_new, test_size=0.2, random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
x_scaler = StandardScaler().fit(x_train)
y_scaler = StandardScaler().fit(y_train)

In [23]:
x_scaler

StandardScaler()

In [24]:
x_train_scaler = x_scaler.transform(x_train).astype(np.float32)
x_test_scaler = x_scaler.transform(x_test).astype(np.float32)
y_train_scaler = y_scaler.transform(y_train).astype(np.float32)
y_test_scaler = y_scaler.transform(y_test).astype(np.float32)

In [25]:
!python3 -m pip install torch


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [26]:
import torch

In [27]:
x_train_tensor = torch.from_numpy(x_train_scaler)

In [28]:
type(x_train_tensor)

torch.Tensor

In [29]:
x_train_tensor

tensor([[-0.6277, -0.6820, -0.4487,  ..., -0.0493, -0.0639, -1.5592],
        [ 0.5632,  1.4300, -1.3241,  ...,  1.1831,  0.6207,  0.4829],
        [ 1.3523, -0.6820, -0.4487,  ...,  1.1831, -1.4758,  1.1635],
        ...,
        [-1.0622,  1.4300,  0.4268,  ..., -0.0493, -1.2117, -1.2188],
        [-0.7579,  0.7260,  0.4268,  ..., -1.2817,  0.7054, -1.2188],
        [-1.1589,  0.7260, -1.3241,  ..., -1.2817, -1.1701,  0.8232]])

In [30]:
x_test_tensor = torch.from_numpy(x_test_scaler)
y_train_tensor = torch.from_numpy(y_train_scaler)
y_test_tensor = torch.from_numpy(y_test_scaler)

In [31]:
import torch.nn as nn

In [47]:
class HousePricePredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(8,16),
            nn.ReLU(),
            nn.Linear(16,8),
            nn.ReLU(),
            nn.Linear(8,4),
            nn.ReLU(),
            nn.Linear(4,1)
            
        )
        
    def forward(self, x_train_data):
        return self.network(x_train_data)

        

In [48]:
model = HousePricePredictor()

In [50]:
model

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=8, bias=True)
    (3): ReLU()
    (4): Linear(in_features=8, out_features=4, bias=True)
    (5): ReLU()
    (6): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [52]:
for param in model.parameters():
    print (param)

Parameter containing:
tensor([[-0.1546, -0.0532,  0.0184, -0.1826, -0.1062,  0.3338,  0.2829,  0.1830],
        [-0.0963,  0.1374, -0.2614,  0.3063, -0.2714, -0.1071, -0.0497, -0.1968],
        [ 0.2602,  0.1939, -0.3524, -0.0215, -0.1785,  0.2960, -0.0477,  0.0601],
        [ 0.2918,  0.0979,  0.1475,  0.2177, -0.1859, -0.2707,  0.0938,  0.2020],
        [-0.2761,  0.0211, -0.1440, -0.0648, -0.2103,  0.2452, -0.2620, -0.0684],
        [ 0.2166,  0.0655,  0.3279, -0.2051,  0.0869, -0.2196,  0.2215,  0.2832],
        [ 0.1263, -0.3106,  0.1727, -0.2905, -0.0517,  0.1369, -0.1918,  0.2546],
        [ 0.2935, -0.3009,  0.0826, -0.3499, -0.0691,  0.2348, -0.2833, -0.0113],
        [-0.1031,  0.2814, -0.2643,  0.3355, -0.2396,  0.3343,  0.0886,  0.0868],
        [-0.0879, -0.0284, -0.1205, -0.1943, -0.2740,  0.2440, -0.0062,  0.0945],
        [ 0.2517, -0.1567,  0.3105, -0.3352, -0.0059, -0.0546,  0.0477, -0.1743],
        [-0.0404, -0.0522, -0.2539,  0.1859, -0.3268,  0.1520,  0.0732,  0.3

In [53]:
criterion = nn.MSELoss()

In [54]:
import torch.optim as optim

In [55]:
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [56]:
model.train()

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=8, bias=True)
    (3): ReLU()
    (4): Linear(in_features=8, out_features=4, bias=True)
    (5): ReLU()
    (6): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [57]:
epochs = 100

In [59]:

for epoch in range(1, epochs + 1):
    y_predictions = model(x_train_tensor)

    loss = criterion(y_predictions, y_train_tensor)
    

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 100, Loss: 0.2306


In [60]:
rows = []
for name, param in model.named_parameters():
    rows.append({
        "Name": name,
        "Shape": tuple(param.shape),
        "Trainable": param.requires_grad,
        "Values (first 5)": [round(v.item(), 4) for v in param.data.flatten()[:5]],
        "Grad (first 5)": None if param.grad is None else [round(g.item(), 4) for g in param.grad.flatten()[:5]]
    })

# Convert to DataFrame for clean display
df = pd.DataFrame(rows)
print(df.to_string(index=False))

            Name   Shape  Trainable                            Values (first 5)                                Grad (first 5)
network.0.weight (16, 8)       True [-0.3592, -0.2994, 0.1481, -0.0911, 0.0625]   [-0.0016, 0.0043, -0.0023, -0.0036, -0.004]
  network.0.bias   (16,)       True     [0.2821, 0.3538, 0.2427, 0.0379, 0.331]   [0.0005, 0.0013, -0.0012, -0.0007, -0.0012]
network.2.weight (8, 16)       True   [-0.2557, 0.0202, 0.2562, 0.0069, 0.1402] [-0.0011, -0.0007, -0.0006, -0.0012, -0.0017]
  network.2.bias    (8,)       True   [-0.0423, 0.2973, 0.0642, 0.3917, 0.2654]  [-0.0024, -0.0047, 0.0003, -0.0035, -0.0006]
network.4.weight  (4, 8)       True [-0.0837, -0.1492, 0.3754, -0.2263, 0.4197]    [0.0005, 0.0055, -0.0054, 0.0007, -0.0109]
  network.4.bias    (4,)       True           [-0.1321, 0.3652, 0.3653, 0.0369]                [0.0008, -0.0005, -0.001, 0.0]
network.6.weight  (1, 4)       True           [-0.4859, 0.2621, 0.286, -0.3532]               [0.0173, -0.0141, -0.012

In [61]:
model.eval()
with torch.no_grad():
    y_pred_test = model(x_test_tensor)
    y_pre_numpy = y_pred_test.numpy()
y_pre_numpy

array([[ 9.71285701e-01],
       [-2.71162570e-01],
       [ 1.13421977e+00],
       [ 1.23473728e+00],
       [ 5.64825058e-01],
       [ 6.97705030e-01],
       [ 1.29729772e+00],
       [ 9.01377559e-01],
       [ 5.49800754e-01],
       [ 9.44987893e-01],
       [ 4.66001779e-01],
       [ 2.55100816e-01],
       [-1.26372564e+00],
       [ 1.48717034e+00],
       [-4.05083954e-01],
       [-1.25671387e+00],
       [-4.13371056e-01],
       [-8.42610836e-01],
       [ 6.37985349e-01],
       [-1.06850982e+00],
       [ 5.08671880e-01],
       [-2.74015129e-01],
       [ 4.85006660e-01],
       [ 6.39315486e-01],
       [-5.49744904e-01],
       [-1.04548323e+00],
       [-3.57577950e-01],
       [-6.34323835e-01],
       [-1.28481150e+00],
       [-7.16689587e-01],
       [-1.31363463e+00],
       [ 1.02505457e+00],
       [ 5.48678279e-01],
       [-9.37489152e-01],
       [-4.12006289e-01],
       [ 5.37941813e-01],
       [-8.50049019e-01],
       [-4.00935382e-01],
       [-1.1

In [62]:
y_pred_test = y_scaler.inverse_transform(y_pre_numpy).flatten()
y_pred_test

array([658461.4 , 395006.47, 693010.75, 714324.94, 572273.44, 600450.  ,
       727590.6 , 643637.7 , 569087.6 , 652885.06, 551318.44, 506597.97,
       184538.47, 767852.1 , 366609.12, 186025.28, 364851.88, 273833.75,
       587786.7 , 225933.  , 560366.44, 394401.6 , 555348.4 , 588068.75,
       335934.5 , 230815.67, 376682.53, 317999.94, 180067.31, 300534.7 ,
       173955.5 , 669862.8 , 568849.6 , 253715.27, 365141.25, 566573.  ,
       272256.5 , 367488.8 , 218154.08, 181093.1 , 208312.75, 180398.4 ,
       363399.38, 180736.38, 790093.2 , 705513.56, 603412.75, 606713.25,
       730149.75, 517020.84, 195849.6 , 525530.9 , 621262.2 , 611230.56,
       330076.44, 603782.75, 178332.75, 179018.9 , 521520.22, 194805.84,
       688015.4 , 250294.97, 186933.44, 339397.8 , 450023.3 , 424052.6 ,
       296632.44, 539535.7 , 646518.5 , 546638.4 , 372204.78, 690306.6 ,
       237005.22, 409795.38, 484771.5 , 515894.94, 385169.47, 209852.14,
       415742.9 , 695970.25, 369649.88, 246189.4 , 

In [63]:
torch.save(model.state_dict(), 'house.pth')