In [1]:
!python3 -m pip install pandas

  Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 42.8 MB/s  0:00:00eta 0:00:01
Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("house_data.csv")

In [4]:
data.head()

,sqft,bedrooms,bathrooms,age,floors,garage,lot_size,city_index,price
0,1360,2,4,18,1,0,5566,1,248990
1,4272,3,4,29,2,2,2909,0,941769
2,3592,1,4,13,2,1,7364,8,378015
3,966,1,4,19,1,0,3581,0,196887
4,4926,2,4,48,1,1,1691,3,1063441


In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sqft        1000 non-null   int64
 1   bedrooms    1000 non-null   int64
 2   bathrooms   1000 non-null   int64
 3   age         1000 non-null   int64
 4   floors      1000 non-null   int64
 5   garage      1000 non-null   int64
 6   lot_size    1000 non-null   int64
 7   city_index  1000 non-null   int64
 8   price       1000 non-null   int64
dtypes: int64(9)
memory usage: 70.4 KB


In [6]:
X = data.drop(columns=['price'])

In [7]:
X.head()

,sqft,bedrooms,bathrooms,age,floors,garage,lot_size,city_index
0,1360,2,4,18,1,0,5566,1
1,4272,3,4,29,2,2,2909,0
2,3592,1,4,13,2,1,7364,8
3,966,1,4,19,1,0,3581,0
4,4926,2,4,48,1,1,1691,3


In [8]:
Y = data[['price']]

In [9]:
Y.head()

,price
0,248990
1,941769
2,378015
3,196887
4,1063441


In [10]:
type(X)

pandas.DataFrame

In [11]:
!python3 -m pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [12]:
import numpy as np

In [13]:
X_new = X.to_numpy(dtype=np.float32)

In [14]:
Y_new = Y.to_numpy(dtype=np.float32)

In [16]:
type(X_new)

numpy.ndarray

In [17]:
type(Y_new)

numpy.ndarray

In [18]:
X_new

array([[1.360e+03, 2.000e+00, 4.000e+00, ..., 0.000e+00, 5.566e+03,
        1.000e+00],
       [4.272e+03, 3.000e+00, 4.000e+00, ..., 2.000e+00, 2.909e+03,
        0.000e+00],
       [3.592e+03, 1.000e+00, 4.000e+00, ..., 1.000e+00, 7.364e+03,
        8.000e+00],
       ...,
       [2.606e+03, 4.000e+00, 4.000e+00, ..., 1.000e+00, 1.495e+03,
        0.000e+00],
       [4.723e+03, 5.000e+00, 2.000e+00, ..., 0.000e+00, 3.148e+03,
        9.000e+00],
       [3.268e+03, 4.000e+00, 3.000e+00, ..., 2.000e+00, 1.556e+03,
        2.000e+00]], shape=(1000, 8), dtype=float32)

In [19]:
!python3 -m pip install scikit-learn


  Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
  Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn] [scikit-learn]

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X_new, Y_new, test_size=0.2, random_state=42)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
x_scaler = StandardScaler().fit(x_train)
y_scaler = StandardScaler().fit(y_train)

In [24]:
x_scaler

StandardScaler()

In [34]:
x_train_scaler = x_scaler.transform(x_train).astype(np.float32)
x_test_scaler = x_scaler.transform(x_test).astype(np.float32)
y_train_scaler = y_scaler.transform(y_train).astype(np.float32)
y_test_scaler = y_scaler.transform(y_test).astype(np.float32)

In [35]:
!python3 -m pip install torch


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [36]:
import torch

In [37]:
x_train_tensor = torch.from_numpy(x_train_scaler)

In [38]:
type(x_train_tensor)

torch.Tensor

In [39]:
x_train_tensor

tensor([[-0.6277, -0.6820, -0.4487,  ..., -0.0493, -0.0639, -1.5592],
        [ 0.5632,  1.4300, -1.3241,  ...,  1.1831,  0.6207,  0.4829],
        [ 1.3523, -0.6820, -0.4487,  ...,  1.1831, -1.4758,  1.1635],
        ...,
        [-1.0622,  1.4300,  0.4268,  ..., -0.0493, -1.2117, -1.2188],
        [-0.7579,  0.7260,  0.4268,  ..., -1.2817,  0.7054, -1.2188],
        [-1.1589,  0.7260, -1.3241,  ..., -1.2817, -1.1701,  0.8232]])

In [41]:
x_test_tensor = torch.from_numpy(x_test_scaler)
y_train_tensor = torch.from_numpy(y_train_scaler)
y_test_tensor = torch.from_numpy(y_test_scaler)

In [42]:
import torch.nn as nn

In [64]:
class HousePricePredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(8,1),
        )
        
    def forward(self, x_train_data):
        return self.network(x_train_data)

        

In [65]:
model = HousePricePredictor()

In [66]:
model

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=1, bias=True)
  )
)

In [67]:
for param in model.parameters():
    print (param)

Parameter containing:
tensor([[ 0.1548, -0.1592,  0.0545, -0.0993,  0.1203, -0.3519, -0.0622, -0.0317]],
       requires_grad=True)
Parameter containing:
tensor([-0.0828], requires_grad=True)


In [68]:
criterion = nn.MSELoss()

In [69]:
import torch.optim as optim

In [70]:
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [71]:
print("y_predictions:", y_predictions)
print("y_train_tensor:", y_train_tensor)

print(type(y_predictions))
print(type(y_train_tensor))

y_predictions: None
y_train_tensor: tensor([[-6.8785e-01],
        [ 8.1758e-01],
        [ 1.7714e+00],
        [ 1.7366e-01],
        [-2.7583e-01],
        [-1.3223e+00],
        [-1.5818e+00],
        [ 1.3501e+00],
        [-1.3041e+00],
        [ 1.0362e+00],
        [-8.8986e-01],
        [-6.6509e-01],
        [-7.9361e-01],
        [ 5.4014e-01],
        [-4.7095e-01],
        [-1.5124e+00],
        [-1.9227e+00],
        [-1.0104e+00],
        [-6.2411e-01],
        [ 6.7587e-01],
        [-1.4465e+00],
        [-8.6895e-01],
        [ 1.5903e-01],
        [-5.8875e-02],
        [-1.0737e+00],
        [-3.5129e-01],
        [ 2.0810e+00],
        [ 1.7609e-02],
        [-7.6795e-01],
        [-1.3468e+00],
        [ 1.2895e+00],
        [-2.5041e-01],
        [-5.9638e-01],
        [-2.2957e-01],
        [-1.3143e+00],
        [ 1.3550e+00],
        [ 2.6295e-01],
        [ 1.2746e+00],
        [-1.6051e+00],
        [-5.2927e-01],
        [-1.2055e+00],
        [-4.5174e-01]

In [72]:
model.train()

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=1, bias=True)
  )
)

In [73]:
epochs = 100

In [75]:

for epoch in range(1, epochs + 1):
    y_predictions = model(x_train_tensor)

    loss = criterion(y_predictions, y_train_tensor)
    

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 100, Loss: 0.5502


In [76]:
rows = []
for name, param in model.named_parameters():
    rows.append({
        "Name": name,
        "Shape": tuple(param.shape),
        "Trainable": param.requires_grad,
        "Values (first 5)": [round(v.item(), 4) for v in param.data.flatten()[:5]],
        "Grad (first 5)": None if param.grad is None else [round(g.item(), 4) for g in param.grad.flatten()[:5]]
    })

# Convert to DataFrame for clean display
df = pd.DataFrame(rows)
print(df.to_string(index=False))

            Name  Shape  Trainable                          Values (first 5)                             Grad (first 5)
network.0.weight (1, 8)       True [0.343, -0.0139, 0.0243, -0.0001, 0.0025] [-1.053, -0.0745, -0.0006, -0.004, 0.0131]
  network.0.bias   (1,)       True                                 [-0.0001]                                  [-0.0003]


In [77]:
model.eval()
with torch.no_grad():
    y_pred_test = model(x_test_tensor)
    y_pre_numpy = y_pred_test.numpy()
y_pre_numpy

array([[ 0.35943586],
       [-0.31618217],
       [ 0.57346904],
       [ 0.3906072 ],
       [ 0.46233314],
       [ 0.0621931 ],
       [ 0.27722648],
       [ 0.3203174 ],
       [ 0.07780194],
       [ 0.39726672],
       [ 0.4970964 ],
       [ 0.09387835],
       [-0.3084928 ],
       [ 0.8267204 ],
       [ 0.16791645],
       [-0.73824364],
       [-0.43844482],
       [-0.10487468],
       [ 0.36194703],
       [-0.35473558],
       [ 0.13528502],
       [-0.3821039 ],
       [ 0.33299023],
       [ 0.6368061 ],
       [ 0.01622375],
       [-0.31651515],
       [-0.46497467],
       [-0.42968678],
       [-0.31055656],
       [-0.45844904],
       [-0.6513013 ],
       [ 0.6795034 ],
       [ 0.21946338],
       [-0.18790157],
       [ 0.08303251],
       [ 0.46470076],
       [-0.18663907],
       [-0.03817449],
       [-0.26353258],
       [-0.7983593 ],
       [-0.38591906],
       [-0.30806196],
       [-0.41090402],
       [-0.24708521],
       [ 0.876511  ],
       [ 0

In [80]:
y_pred_test = y_scaler.inverse_transform(y_pre_numpy).flatten()
y_pred_test

array([528721.7 , 385460.28, 574106.4 , 535331.44, 550540.56, 465692.88,
       511289.6 , 520426.8 , 469002.62, 536743.5 , 557911.94, 472411.56,
       387090.78, 627807.  , 488110.97, 295964.28, 359535.12, 430266.97,
       529254.2 , 377285.22, 481191.62, 371481.9 , 523114.03, 587536.6 ,
       455945.28, 385389.7 , 353909.6 , 361392.2 , 386653.2 , 355293.3 ,
       314399.94, 596590.4 , 499041.22, 412661.53, 470111.75, 551042.56,
       412929.25, 444410.4 , 396624.38, 283217.06, 370672.94, 387182.12,
       365375.  , 400111.94, 638364.9 , 500321.25, 462757.34, 469882.12,
       555208.4 , 495165.06, 341841.66, 479835.25, 556169.06, 523763.22,
       476873.56, 458362.56, 384163.3 , 361469.62, 536727.9 , 393992.6 ,
       515460.72, 433071.72, 346928.1 , 417135.6 , 394398.78, 406010.62,
       341554.1 , 441777.3 , 593182.4 , 474516.1 , 374969.62, 576401.6 ,
       326261.72, 481928.28, 469277.2 , 522342.5 , 459643.22, 335478.56,
       400040.5 , 482813.75, 483062.06, 331345.7 , 

In [81]:
torch.save(model.state_dict(), 'house.pth')